begin;

-- Preserve existing users and give each local demo account a stable app identity.
alter table public.users add column if not exists user_id text;

update public.users
set user_id = 'local-' || id::text
where user_id is null;

alter table public.users alter column user_id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_user_id_key'
      and conrelid = 'public.users'::regclass
  ) then
    alter table public.users
      add constraint users_user_id_key unique (user_id);
  end if;
end
$$;

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  genre text,
  description text
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.booktags (
  book_id bigint not null references public.books(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (book_id, tag_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id text not null references public.users(user_id) on update cascade on delete restrict,
  book_id bigint not null references public.books(id) on delete cascade,
  review_text text not null check (length(trim(review_text)) > 0),
  star_rating integer not null check (star_rating between 1 and 5),
  created_at timestamptz not null default now()
);

create table if not exists public.tbr (
  user_id text not null references public.users(user_id) on update cascade on delete cascade,
  book_id bigint not null references public.books(id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (user_id, book_id)
);

create index if not exists reviews_book_id_idx on public.reviews(book_id);
create index if not exists reviews_user_id_idx on public.reviews(user_id);
create index if not exists tbr_book_id_idx on public.tbr(book_id);

insert into public.books (id, title, author, genre, description) values
  (1, 'Rebecca', 'Daphne du Maurier', 'Gothic mystery', 'A new wife confronts the lingering influence of her husband''s first marriage at an isolated estate.'),
  (2, 'And Then There Were None', 'Agatha Christie', 'Mystery', 'Ten strangers on an island confront a deadly accusation and a shrinking list of survivors.'),
  (3, 'Heartless', 'Marissa Meyer', 'Fantasy', 'A hopeful baker''s daughter faces court politics and a fate that reshapes a familiar fairy tale.'),
  (4, 'Why We Sleep', 'Matthew Walker', 'Science nonfiction', 'A sleep researcher explains how rest supports memory, health, emotion, and daily performance.'),
  (5, 'Fahrenheit 451', 'Ray Bradbury', 'Dystopian fiction', 'A fireman assigned to destroy books begins to question the culture that fears independent thought.'),
  (6, 'Animal Farm', 'George Orwell', 'Political fiction', 'Farm animals build a new society only to discover how power can recreate old injustices.'),
  (7, 'Pride and Prejudice', 'Jane Austen', 'Romance', 'A sharp-witted young woman and a reserved gentleman challenge each other''s first impressions.'),
  (8, 'The Hobbit', 'J. R. R. Tolkien', 'Fantasy', 'A comfort-loving hobbit joins a quest to reclaim treasure guarded by a dragon.'),
  (9, 'The Book Thief', 'Markus Zusak', 'Historical fiction', 'In wartime Germany, a young girl finds courage and connection through stolen books and shared stories.'),
  (10, 'The Martian', 'Andy Weir', 'Science fiction', 'An astronaut stranded on Mars uses ingenuity and science to stay alive and seek rescue.'),
  (11, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Literary fiction', 'A newcomer to Long Island watches wealth, longing, and illusion collide around a mysterious neighbor.'),
  (12, 'The Midnight Library', 'Matt Haig', 'Fantasy', 'A regretful woman explores possible lives in a library that sits between despair and new choices.'),
  (13, 'The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'Historical fiction', 'A retired screen icon reveals the compromises and relationships behind her carefully guarded life.'),
  (14, 'Educated', 'Tara Westover', 'Memoir', 'A woman raised in an isolated household pursues education while reexamining family loyalty and selfhood.'),
  (15, 'Sapiens', 'Yuval Noah Harari', 'Nonfiction', 'A broad history considers the ideas, systems, and stories that shaped human societies.'),
  (16, 'Atomic Habits', 'James Clear', 'Self-help', 'A practical guide argues that small, repeatable choices can compound into meaningful change.'),
  (17, 'The Song of Achilles', 'Madeline Miller', 'Historical fiction', 'A reimagining of Greek myth follows the bond between Patroclus and Achilles through war and loss.'),
  (18, 'The Name of the Wind', 'Patrick Rothfuss', 'Fantasy', 'A gifted storyteller recounts the beginnings of his unusual education, friendships, and legend.'),
  (19, 'The Silent Patient', 'Alex Michaelides', 'Psychological thriller', 'A therapist becomes consumed by the silence of a celebrated painter accused of violence.'),
  (20, 'A Brief History of Time', 'Stephen Hawking', 'Science nonfiction', 'An accessible exploration of space, time, gravity, and questions about the universe.')
on conflict (id) do update
set title = excluded.title,
    author = excluded.author,
    genre = excluded.genre,
    description = excluded.description;

select setval(
  pg_get_serial_sequence('public.books', 'id'),
  greatest((select coalesce(max(id), 1) from public.books), 1),
  true
);

insert into public.tags (name) values
  ('Fiction'), ('Nonfiction'), ('Fantasy'), ('Romance'), ('Mystery'),
  ('Thriller'), ('Science'), ('Educational'), ('Self-help'), ('Historical'),
  ('Dystopian'), ('Biography'), ('Adventure')
on conflict (name) do nothing;

with desired_tags (book_id, tag_name) as (
  values
    (1, 'Fiction'), (1, 'Mystery'),
    (2, 'Fiction'), (2, 'Mystery'), (2, 'Thriller'),
    (3, 'Fiction'), (3, 'Fantasy'), (3, 'Romance'),
    (4, 'Nonfiction'), (4, 'Science'), (4, 'Educational'),
    (5, 'Fiction'), (5, 'Dystopian'),
    (6, 'Fiction'), (6, 'Dystopian'), (6, 'Historical'),
    (7, 'Fiction'), (7, 'Romance'),
    (8, 'Fiction'), (8, 'Fantasy'), (8, 'Adventure'),
    (9, 'Fiction'), (9, 'Historical'),
    (10, 'Fiction'), (10, 'Science'), (10, 'Adventure'),
    (11, 'Fiction'), (11, 'Historical'),
    (12, 'Fiction'), (12, 'Fantasy'),
    (13, 'Fiction'), (13, 'Historical'), (13, 'Romance'),
    (14, 'Nonfiction'), (14, 'Biography'), (14, 'Educational'),
    (15, 'Nonfiction'), (15, 'Science'), (15, 'Educational'),
    (16, 'Nonfiction'), (16, 'Self-help'), (16, 'Educational'),
    (17, 'Fiction'), (17, 'Historical'), (17, 'Romance'),
    (18, 'Fiction'), (18, 'Fantasy'), (18, 'Adventure'),
    (19, 'Fiction'), (19, 'Mystery'), (19, 'Thriller'),
    (20, 'Nonfiction'), (20, 'Science'), (20, 'Educational')
)
insert into public.booktags (book_id, tag_id)
select desired_tags.book_id, tags.id
from desired_tags
join public.tags on tags.name = desired_tags.tag_name
on conflict (book_id, tag_id) do nothing;

-- Existing users remain unchanged and unrestricted. TBR is new, so enable RLS
-- without a broad policy; future API work should use an authenticated identity
-- or a server-only database client to create user-scoped policies.
alter table public.tbr enable row level security;

commit;
